---
# Source: opentelemetry-demo/charts/grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: otel-servicenow-collector
  labels:
    app.kubernetes.io/name: otel-servicenow-collector
    app.kubernetes.io/version: "0.1.0"
type: Opaque
stringData:
  lightstep-api-key: "eyJhbGciOiJIUzI1NiIsImtpZCI6IjIwMTktMDMtMDEiLCJ0eXAiOiJKV1QifQ.eyJzY3AiOnsicm9sZSI6ImU1MTI5ODNiLTFjYjktMTFlOC05M2Y1LTQyMDEwYWYwMGFkNiJ9LCJ2ZXIiOjEsImRlYnVnIjp7Im9yZyI6IkxpZ2h0U3RlcCIsInJvbGUiOiJPcmdhbml6YXRpb24gQWRtaW4ifSwiYXVkIjoiYXBwLmxpZ2h0c3RlcC5jb20iLCJleHAiOjE2OTc2NDI3NDIsImp0aSI6ImJ3em8yN2l5eGpsaGV1NzI2Mm5rbjJoYnRkbDJ1ZjNlemluN3dweXZydXZlcmJsNiIsImlhdCI6MTY2NjEwNjc0MiwiaXNzIjoibGlnaHRzdGVwLmNvbSIsInN1YiI6IjEyOWY2ZWIzNGE3ZGJjZDcxZTI2NDM1Yzc4OSJ9.iKoCc_MMJ8iKvyIr4093jxiNtB6LIVQWPZgjBwritJc"
