---
# Source: opentelemetry-collector/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-servicenow-collector
  labels:
    app.kubernetes.io/name: otel-servicenow-collector
    app.kubernetes.io/version: "0.1.0"
