  exporters:
    logging:
      logLevel: debug
    otlp/lightstep:
      endpoint: ingest.lightstep.com:443
      headers:
        "lightstep-access-token": "${LIGHTSTEP_ACCESS_TOKEN}"

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [logging, otlp/lightstep]
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [logging, otlp/lightstep]
